# Generated by Django 5.1.2 on 2025-11-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_instapost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentNew',
        ),
        migrations.DeleteModel(
            name='InstaPost',
        ),
    ]
